List1 = ['Asuka' , 'Kevin' , 'EZ' , 'White' , 'Coco' , 'England']
print(List1[0])
print(f'I love {List1[0]}')
List1.append('Dave')
print(List1)
List1.insert(1 , 'Paris')
print(List1)
List1.pop(3)
print(List1)
pop_list = List1.pop()
print(List1)
List1.remove('Coco')
print(sorted(List1))
print(List1)
print (sorted(List1 , reverse=True))
print(List1)
(List1.reverse())
print(List1)
(List1.reverse())
print(List1)
List1.sort()
print(List1)
List1.sort(reverse=True)
print(List1)

